name: rent_a
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.3.2
  animations: ^2.0.11
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
